module Top;
  logic and_tt, and_tf, and_ff;
  logic or_tt, or_tf, or_ff;
  logic not_t, not_f;
  logic and_zero_dominates, and_one_with_x, and_x_x;
  logic or_one_dominates, or_zero_with_x, or_x_x;
  logic not_x;
  initial begin
    logic [3:0] a;
    logic [3:0] b;
    a = 4'b1010; b = 4'b0011;
    and_tt = a && b;
    a = 4'b1010; b = 4'b0000;
    and_tf = a && b;
    a = 4'b0000; b = 4'b0000;
    and_ff = a && b;
    a = 4'b1010; b = 4'b0011;
    or_tt = a || b;
    a = 4'b1010; b = 4'b0000;
    or_tf = a || b;
    a = 4'b0000; b = 4'b0000;
    or_ff = a || b;
    a = 4'b1010;
    not_t = !a;
    a = 4'b0000;
    not_f = !a;
    a = 4'b0000; b = 4'bxxxx;
    and_zero_dominates = a && b;
    a = 4'b0001; b = 4'bxxxx;
    and_one_with_x = a && b;
    a = 4'bxxxx; b = 4'bxxxx;
    and_x_x = a && b;
    a = 4'b0001; b = 4'bxxxx;
    or_one_dominates = a || b;
    a = 4'b0000; b = 4'bxxxx;
    or_zero_with_x = a || b;
    a = 4'bxxxx; b = 4'bxxxx;
    or_x_x = a || b;
    a = 4'bxxxx;
    not_x = !a;
  end
endmodule
