name: Bazel File Lint

on:
  push:
    branches: [main]
    paths:
      - "**/BUILD.bazel"
      - "MODULE.bazel"
      - ".bazelrc"
      - ".bazelignore"
      - ".bazelversion"
      - ".github/workflows/bazel-lint.yml"
  pull_request:
    branches: [main]
    paths:
      - "**/BUILD.bazel"
      - "MODULE.bazel"
      - ".bazelrc"
      - ".bazelignore"
      - ".bazelversion"
      - ".github/workflows/bazel-lint.yml"

jobs:
  lint:
    name: Buildifier Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup buildifier
        uses: jbajic/setup-buildifier@v1
        with:
          buildifier-version: "8.2.1"

      - name: Run buildifier
        id: buildifier
        run: |
          set -o pipefail
          RESULT=$(buildifier -mode=check -lint=warn -r . 2>&1) || {
            echo "Buildifier found issues:" >> $GITHUB_STEP_SUMMARY
            echo "```" >> $GITHUB_STEP_SUMMARY
            echo "$RESULT" >> $GITHUB_STEP_SUMMARY
            echo "```" >> $GITHUB_STEP_SUMMARY
            echo "$RESULT"
            exit 1
          }

          if [ -z "$RESULT" ]; then
            echo "No issues found by buildifier" >> $GITHUB_STEP_SUMMARY
          else
            echo "Buildifier output:" >> $GITHUB_STEP_SUMMARY
            echo "```" >> $GITHUB_STEP_SUMMARY
            echo "$RESULT" >> $GITHUB_STEP_SUMMARY
            echo "```" >> $GITHUB_STEP_SUMMARY
          fi
