name: Bazel File Lint

on:
  push:
    branches: [main]
    paths:
      - "**/BUILD.bazel"
      - "MODULE.bazel"
      - ".bazelrc"
      - ".bazelignore"
      - ".bazelversion"
      - ".github/workflows/bazel-lint.yml"
  pull_request:
    branches: [main]
    paths:
      - "**/BUILD.bazel"
      - "MODULE.bazel"
      - ".bazelrc"
      - ".bazelignore"
      - ".bazelversion"
      - ".github/workflows/bazel-lint.yml"

jobs:
  lint:
    name: Buildifier Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup buildifier
        run: |
          wget -q https://github.com/bazelbuild/buildtools/releases/download/v8.2.1/buildifier-linux-amd64
          chmod +x buildifier-linux-amd64
          sudo mv buildifier-linux-amd64 /usr/local/bin/buildifier
          buildifier --version

      - name: Check formatting
        id: format
        run: |
          # Check formatting only
          if ! buildifier -mode=check -r .; then
            echo "### ❌ Formatting issues detected" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Run the following command locally to fix formatting:" >> $GITHUB_STEP_SUMMARY
            echo "```" >> $GITHUB_STEP_SUMMARY
            echo "buildifier -r ." >> $GITHUB_STEP_SUMMARY
            echo "```" >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "### ✅ Formatting check passed" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Check lint warnings
        id: lint
        run: |
          # Check for lint warnings
          LINT_OUTPUT=$(buildifier -mode=check -lint=warn -r . 2>&1)
          EXIT_CODE=$?

          if [ $EXIT_CODE -ne 0 ]; then
            echo "### ❌ Lint warnings detected" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "```" >> $GITHUB_STEP_SUMMARY
            echo "$LINT_OUTPUT" >> $GITHUB_STEP_SUMMARY
            echo "```" >> $GITHUB_STEP_SUMMARY

            # Also print to console
            echo "$LINT_OUTPUT"
            exit 1
          else
            echo "### ✅ Lint check passed" >> $GITHUB_STEP_SUMMARY
          fi
